{
    "InternalException.html": {
        "modified": "2021-07-24 18:49:52.714741",
        "size": "13.76KB",
        "md5": "695c66c4609dbb1f29315b242ca990c0",
        "sha256": "58e71dce289822d2baad930d09a3746081c5efac2ac4d18a96ee60d54b67166a"
    },
    "Metadata": {
        "Content-Encoding": "ISO-8859-1",
        "Content-Type": "text/html; charset=ISO-8859-1",
        "X-Parsed-By": [
            "org.apache.tika.parser.DefaultParser",
            "org.apache.tika.parser.html.HtmlParser"
        ],
        "X-TIKA:content_handler": "ToTextContentHandler",
        "X-TIKA:embedded_depth": "0",
        "X-TIKA:parse_time_millis": "5",
        "dc:title": "InternalException (Axis API)",
        "keywords": "org.apache.axis.InternalException class",
        "resourceName": "b'InternalException.html'",
        "title": "InternalException (Axis API)"
    }
}