{
    "ConfigurationException.html": {
        "modified": "2021-07-24 18:49:52.718074",
        "size": "64.82KB",
        "md5": "71bc6325f881144c4023cc9a28a46a53",
        "sha256": "4163c5483a174974dbd2e8517d6354ceff4b41d57cb1bbf5b88d6df1e91eebff"
    },
    "Metadata": {
        "Content-Encoding": "ISO-8859-1",
        "Content-Type": "text/html; charset=ISO-8859-1",
        "X-Parsed-By": [
            "org.apache.tika.parser.DefaultParser",
            "org.apache.tika.parser.html.HtmlParser"
        ],
        "X-TIKA:content_handler": "ToTextContentHandler",
        "X-TIKA:embedded_depth": "0",
        "X-TIKA:parse_time_millis": "6",
        "dc:title": "Uses of Class org.apache.axis.ConfigurationException (Axis API)",
        "resourceName": "b'ConfigurationException.html'",
        "title": "Uses of Class org.apache.axis.ConfigurationException (Axis API)"
    }
}