{
    "InvokeException.html": {
        "modified": "2021-07-24 18:49:52.774740",
        "size": "7.62KB",
        "md5": "6faf14b299c6cd724dacad11873679d2",
        "sha256": "ba80896e1403bfeb1efed7d151a6dc8cf16c74d5ed4056f1d4a88f13389e3b38"
    },
    "Metadata": {
        "Content-Encoding": "ISO-8859-1",
        "Content-Type": "text/html; charset=ISO-8859-1",
        "X-Parsed-By": [
            "org.apache.tika.parser.DefaultParser",
            "org.apache.tika.parser.html.HtmlParser"
        ],
        "X-TIKA:content_handler": "ToTextContentHandler",
        "X-TIKA:embedded_depth": "0",
        "X-TIKA:parse_time_millis": "1",
        "dc:title": "Uses of Class org.apache.axis.transport.jms.InvokeException (Axis API)",
        "resourceName": "b'InvokeException.html'",
        "title": "Uses of Class org.apache.axis.transport.jms.InvokeException (Axis API)"
    }
}